package:
  name: magetab-curation-scripts
  version: "0.0.1"

source:
  git_url: https://github.com/ebi-gene-expression-group/perl-curation-scripts.git

build:
  number: 0

requirements:
  build:
    - perl-atlas-modules
  host:
    - perl=5.26.2
  run:
    - perl-atlas-modules
