{% set version = '0.4.36' %}

package:
  name: ucsc-cell-browser
  version: {{ version }}

source:
  url: https://github.com/maximilianh/cellBrowser/archive/v{{ version }}.tar.gz
  sha256: 93507d1551c4f63c313812e679591a8710619f0a84ddb0d05d80e1354a6b694a 

build:
  number: 0
  noarch: python

requirements:
    host:
        - python >=3.6
    run:
        - python >=3.6
        - numpy
        - anndata

test:
    commands:
        - which cbBuild
        - which cbGuessGencode
        - which cbImportSeurat
        - which cbMarkerAnnotate
        - which cbScanpy
        - which cbImportScanpy
        - which cbImportCellranger
        - which cbTool
        - which cbUpgrade

about:
  home: http://cells.ucsc.edu
  license: GPL
  license_file: LICENSE
  summary: A browser for single-cell data, main site at http://cells.ucsc.edu
